interface Constants {
  READING_LIST_MAX_CHARS: number;
  READING_LIST_MIN_CHARS: number;

  BOOK_TITLE_MAX_CHARS: number;
  BOOK_TITLE_MIN_CHARS: number;

  BOOK_AUTHOR_MAX_CHARS: number;
  BOOK_AUTHOR_MIN_CHARS: number;
}

export const consts: Constants = {
  READING_LIST_MAX_CHARS: 50,
  READING_LIST_MIN_CHARS: 2,

  BOOK_TITLE_MAX_CHARS: 200,
  BOOK_TITLE_MIN_CHARS: 5,

  BOOK_AUTHOR_MAX_CHARS: 200,
  BOOK_AUTHOR_MIN_CHARS: 2,
};
